### ISSUE TITLE
getting data other than 2015

### ISSUE THREAD

**Issue by dodecaploid** [aaronferrucci/wharf2wharf#1]
I love your code for 2015! Very easy to use, but for some reason I can't get data for 2016. Is the URL hard coded to 2015?

**Comment by aaronferrucci** [comment]
Yes, the scraping code is hard-coded to 2015. The reason: I've seen the structure of the web site change for different years. I do plan to support 2016, soonish!

**Comment by dodecaploid** [comment]
Awesome. I quite like the tool! Thanks for posting and and supporting it.

Cheers,
Jud

Judson Ward,
PhD
Principal Scientist, Molecular Biology
Driscoll's, 151 Silliman Rd
Watsonville, CA
95076
Phone: 831.722.5577 | Cell:
831.254.9364
Judson.ward@driscolls.com

www.driscolls.com

**Comment by aaronferrucci** [comment]
I've updated the scraping code to support 2016 as well as 2015. The write-up is still very 2015-specific, but you can have a look at the 2016 data by doing:

```
source("w2w_utils.R")
data2016 <- getData(2016)
```

Then you can play with the 2016 data in a similar manner to what's done for 2015 (w2w.Rmd). 

I'm going to look into a full write-up, specific to 2016, but I wanted to get this change in as soon as possible. Let me know if you see any problems, thanks!

**Comment by areeves87** [comment]
Is there any chance you could leave some tips for how to do this for 2017? I love being able to play around with this data but I'm a total beginner and I can't figure out how to write out the json queries. Specifically, I want to know how you found out the eventids, subeventids, categoryid, and the long jquery digit string.

**Comment by aaronferrucci** [comment]
I figured out the query by using the browser's debug console. It's pretty tedious, but you can see a lot of what's happening "behind the scenes".

**Comment by dodecaploid** [comment]
Excellent. Is there an update in github? I unfortunately was out of town
for the run this year, but many friends did it so I might analyze the data
anyway.

Best,
Jud

Judson Ward,
PhD
Principal Scientist, Molecular Biology
Driscoll's, 151 Silliman Rd
Watsonville, CA
95076
Phone: 831.722.5577 | Cell:
831.254.9364
Judson.ward@driscolls.com

www.driscolls.com

**Comment by aaronferrucci** [comment]
Yes, thanks to areeves87's pull request, the 2017 data is available. It's in w2w2017.csv. But have a look at the two open issues - they have to do with problems I've noticed in the 2017 dataset. I have some ideas for how to clean it up, but if you think of anything, please comment.
